name: denox
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.3.0
  plugin_platform_interface: ^2.0.2
  rust_lib_denox:
    path: rust_builder
  
  # Application
  adaptive_theme: ^3.6.0
  flutter_native_splash: ^2.4.3

  # Status Handler
  provider: ^6.1.2
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1

  # Debug
  talker: ^4.5.2
  talker_flutter: ^4.5.2
  talker_logger: ^4.5.2
  talker_riverpod_logger: ^4.5.2

  # JS Binder
  event_bus: ^2.0.1
  device_info_plus: ^11.1.1
  permission_handler: ^11.3.1
  go_router: ^14.6.1

  # JS Render
  flutter_svg: ^2.0.16

  # JS Native Function
  cross_file: ^0.3.4+2
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  camera: ^0.11.0+2
  geolocator: ^13.0.2
  flutter_local_notifications: ^18.0.1
  # flutter_callkit_incoming: ^2.0.4+2
  record: ^5.2.0
  connectivity_plus: ^6.1.0
  share_plus: ^10.1.2
  local_auth: ^2.3.0
  flutter_tts: ^4.2.0
  wakelock_plus: ^1.2.8
  battery_plus: ^6.2.0
  sensors_plus: ^6.1.0
  background_downloader: ^8.8.0
  flutter_nfc_kit: ^3.5.2
  no_screenshot: ^0.3.1

  # Style Achieve
  auto_size_text_plus: ^3.0.2
  dotted_border: ^2.1.0
  blurrycontainer: ^2.1.0
  gap: ^3.0.1

  # Audio Player
  just_audio: ^0.9.42
  just_audio_background: ^0.0.1-beta.13
  just_audio_media_kit: ^2.0.6
  media_kit_libs_windows_audio: ^1.0.9 # Windows Support
  media_kit_libs_linux: ^1.1.3 # Linux Support

  # Video Player
  video_player_media_kit: ^1.0.5
  media_kit_libs_android_video: ^1.3.6
  media_kit_libs_ios_video: ^1.1.4
  media_kit_libs_macos_video: ^1.1.4
  media_kit_libs_windows_video: ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.hellok.denox.denox
        pluginClass: DenoxPlugin
      ios:
        pluginClass: DenoxPlugin
      linux:
        pluginClass: DenoxPlugin
      macos:
        pluginClass: DenoxPlugin
      windows:
        pluginClass: DenoxPluginCApi

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
